/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'on-tertiary-container': '#4bb278',
        'error': '#ba1a1a',
        'tertiary-fixed-dim': '#74db9d',
        'on-tertiary': '#ffffff',
        'surface-container': '#ebeef0',
        'surface': '#f7fafc',
        'surface-bright': '#f7fafc',
        'tertiary-container': '#003f23',
        'surface-container-low': '#f1f4f6',
        'on-background': '#181c1e',
        'inverse-on-surface': '#eef1f3',
        'surface-dim': '#d7dadc',
        'tertiary': '#002713',
        'on-secondary-container': '#586377',
        'on-primary': '#ffffff',
        'background': '#f7fafc',
        'primary-fixed': '#d6e3ff',
        'outline': '#74777f',
        'on-tertiary-fixed': '#002110',
        'on-surface-variant': '#43474e',
        'on-tertiary-fixed-variant': '#00522f',
        'on-secondary': '#ffffff',
        'surface-tint': '#455f88',
        'on-surface': '#181c1e',
        'on-secondary-fixed-variant': '#3c475a',
        'secondary': '#545f72',
        'on-primary-container': '#86a0cd',
        'secondary-fixed': '#d8e3fa',
        'on-secondary-fixed': '#111c2c',
        'inverse-surface': '#2d3133',
        'on-primary-fixed-variant': '#2d476f',
        'surface-variant': '#e0e3e5',
        'secondary-container': '#d5e0f7',
        'surface-container-high': '#e5e9eb',
        'on-primary-fixed': '#001b3c',
        'inverse-primary': '#adc7f7',
        'primary-container': '#1a365d',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#adc7f7',
        'secondary-fixed-dim': '#bcc7dd',
        'surface-container-highest': '#e0e3e5',
        'outline-variant': '#c4c6cf',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'tertiary-fixed': '#91f8b8',
        'primary': '#002045',
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
        '2xl': '1rem',
      },
    },
  },
  plugins: [],
}
