/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error-container':              'rgb(var(--color-error-container-rgb) / <alpha-value>)',
        'on-tertiary-container':        'rgb(var(--color-on-tertiary-container-rgb) / <alpha-value>)',
        'error':                        'rgb(var(--color-error-rgb) / <alpha-value>)',
        'tertiary-fixed-dim':           'rgb(var(--color-tertiary-fixed-dim-rgb) / <alpha-value>)',
        'on-tertiary':                  'rgb(var(--color-on-tertiary-rgb) / <alpha-value>)',
        'surface-container':            'rgb(var(--color-surface-container-rgb) / <alpha-value>)',
        'surface':                      'rgb(var(--color-surface-rgb) / <alpha-value>)',
        'surface-bright':               'rgb(var(--color-surface-bright-rgb) / <alpha-value>)',
        'tertiary-container':           'rgb(var(--color-tertiary-container-rgb) / <alpha-value>)',
        'surface-container-low':        'rgb(var(--color-surface-container-low-rgb) / <alpha-value>)',
        'on-background':                'rgb(var(--color-on-background-rgb) / <alpha-value>)',
        'inverse-on-surface':           'rgb(var(--color-inverse-on-surface-rgb) / <alpha-value>)',
        'surface-dim':                  'rgb(var(--color-surface-dim-rgb) / <alpha-value>)',
        'tertiary':                     'rgb(var(--color-tertiary-rgb) / <alpha-value>)',
        'on-secondary-container':       'rgb(var(--color-on-secondary-container-rgb) / <alpha-value>)',
        'on-primary':                   'rgb(var(--color-on-primary-rgb) / <alpha-value>)',
        'background':                   'rgb(var(--color-background-rgb) / <alpha-value>)',
        'primary-fixed':                'rgb(var(--color-primary-fixed-rgb) / <alpha-value>)',
        'outline':                      'rgb(var(--color-outline-rgb) / <alpha-value>)',
        'on-tertiary-fixed':            'rgb(var(--color-on-tertiary-fixed-rgb) / <alpha-value>)',
        'on-surface-variant':           'rgb(var(--color-on-surface-variant-rgb) / <alpha-value>)',
        'on-tertiary-fixed-variant':    'rgb(var(--color-on-tertiary-fixed-variant-rgb) / <alpha-value>)',
        'on-secondary':                 'rgb(var(--color-on-secondary-rgb) / <alpha-value>)',
        'surface-tint':                 'rgb(var(--color-surface-tint-rgb) / <alpha-value>)',
        'on-surface':                   'rgb(var(--color-on-surface-rgb) / <alpha-value>)',
        'on-secondary-fixed-variant':   'rgb(var(--color-on-secondary-fixed-variant-rgb) / <alpha-value>)',
        'secondary':                    'rgb(var(--color-secondary-rgb) / <alpha-value>)',
        'on-primary-container':         'rgb(var(--color-on-primary-container-rgb) / <alpha-value>)',
        'secondary-fixed':              'rgb(var(--color-secondary-fixed-rgb) / <alpha-value>)',
        'on-secondary-fixed':           'rgb(var(--color-on-secondary-fixed-rgb) / <alpha-value>)',
        'inverse-surface':              'rgb(var(--color-inverse-surface-rgb) / <alpha-value>)',
        'on-primary-fixed-variant':     'rgb(var(--color-on-primary-fixed-variant-rgb) / <alpha-value>)',
        'surface-variant':              'rgb(var(--color-surface-variant-rgb) / <alpha-value>)',
        'secondary-container':          'rgb(var(--color-secondary-container-rgb) / <alpha-value>)',
        'surface-container-high':       'rgb(var(--color-surface-container-high-rgb) / <alpha-value>)',
        'on-primary-fixed':             'rgb(var(--color-on-primary-fixed-rgb) / <alpha-value>)',
        'inverse-primary':              'rgb(var(--color-inverse-primary-rgb) / <alpha-value>)',
        'primary-container':            'rgb(var(--color-primary-container-rgb) / <alpha-value>)',
        'surface-container-lowest':     'rgb(var(--color-surface-container-lowest-rgb) / <alpha-value>)',
        'primary-fixed-dim':            'rgb(var(--color-primary-fixed-dim-rgb) / <alpha-value>)',
        'secondary-fixed-dim':          'rgb(var(--color-secondary-fixed-dim-rgb) / <alpha-value>)',
        'surface-container-highest':    'rgb(var(--color-surface-container-highest-rgb) / <alpha-value>)',
        'outline-variant':              'rgb(var(--color-outline-variant-rgb) / <alpha-value>)',
        'on-error':                     'rgb(var(--color-on-error-rgb) / <alpha-value>)',
        'on-error-container':           'rgb(var(--color-on-error-container-rgb) / <alpha-value>)',
        'tertiary-fixed':               'rgb(var(--color-tertiary-fixed-rgb) / <alpha-value>)',
        'primary':                      'rgb(var(--color-primary-rgb) / <alpha-value>)',
        'on-secondary-fixed-variant':   'rgb(var(--color-on-secondary-fixed-variant-rgb) / <alpha-value>)',
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
        '2xl': '1rem',
      },
    },
  },
  plugins: [],
}
